eu.xenit.alfresco.healthprocessor.task.cron=* * * * * ? 2099
eu.xenit.alfresco.healthprocessor.task.delay=0

eu.xenit.alfresco.healthprocessor.processing.single-tenant=true
eu.xenit.alfresco.healthprocessor.processing.node-batch-size=1000
eu.xenit.alfresco.healthprocessor.processing.max-batches-per-second=-1
eu.xenit.alfresco.healthprocessor.processing.read-only=true
eu.xenit.alfresco.healthprocessor.processing.run-as-user=System

eu.xenit.alfresco.healthprocessor.indexing.strategy=txn-id

eu.xenit.alfresco.healthprocessor.indexing.txn-id.start=-1
eu.xenit.alfresco.healthprocessor.indexing.txn-id.stop=9223372036854775807
eu.xenit.alfresco.healthprocessor.indexing.txn-id.txn-batch-size=5000

eu.xenit.alfresco.healthprocessor.indexing.last-txns.lookback-transactions=10000
eu.xenit.alfresco.healthprocessor.indexing.last-txns.txn-batch-size=5000

eu.xenit.alfresco.healthprocessor.checker.noop.enabled=false
eu.xenit.alfresco.healthprocessor.checker.content-validation.enabled=false
eu.xenit.alfresco.healthprocessor.checker.content-validation.properties=

eu.xenit.alfresco.healthprocessor.checker.solr-index.enabled=false
eu.xenit.alfresco.healthprocessor.checker.solr-index.check-transaction=false
eu.xenit.alfresco.healthprocessor.checker.solr-index.endpoints=default,archive
eu.xenit.alfresco.healthprocessor.checker.solr-index.endpoints.default.type=Always
eu.xenit.alfresco.healthprocessor.checker.solr-index.endpoints.default.base-uri=https://${solr.host}:${solr.port.ssl}/solr/alfresco
eu.xenit.alfresco.healthprocessor.checker.solr-index.endpoints.default.indexed-store=workspace://SpacesStore

eu.xenit.alfresco.healthprocessor.checker.solr-index.endpoints.archive.type=Always
eu.xenit.alfresco.healthprocessor.checker.solr-index.endpoints.archive.base-uri=https://${solr.host}:${solr.port.ssl}/solr/archive
eu.xenit.alfresco.healthprocessor.checker.solr-index.endpoints.archive.indexed-store=archive://SpacesStore

# not defined in base repository.properties or Enterprise one
elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.baseUrl=/
elasticsearch.secureComms=none

# no (default) setup for the archive here
# indexing is dependent on events, events on behaviours, which are disabled for archive store
elasticsearch.indexName=alfresco

eu.xenit.alfresco.healthprocessor.checker.elastic-index.enabled=false
eu.xenit.alfresco.healthprocessor.checker.elastic-index.endpoints=default
eu.xenit.alfresco.healthprocessor.checker.elastic-index.endpoints.default.base-uri=${elasticsearch.host}:${elasticsearch.port}${elasticsearch.baseUrl}${elasticsearch.indexName}
eu.xenit.alfresco.healthprocessor.checker.elastic-index.endpoints.default.secureComms=${elasticsearch.secureComms}
eu.xenit.alfresco.healthprocessor.checker.elastic-index.endpoints.default.expect-paths-indexed=false

eu.xenit.alfresco.healthprocessor.reporter.store.max-stored-reports=3000
eu.xenit.alfresco.healthprocessor.reporter.alfred-telemetry.enabled=false
eu.xenit.alfresco.healthprocessor.reporter.log.summary.enabled=false
eu.xenit.alfresco.healthprocessor.reporter.log.progress.enabled=false
eu.xenit.alfresco.healthprocessor.reporter.log.streaming.enabled=false

eu.xenit.alfresco.healthprocessor.fixer.solr-missing-node.enabled=false
eu.xenit.alfresco.healthprocessor.fixer.solr-duplicate-node.enabled=false

eu.xenit.alfresco.healthprocessor.fixer.elastic-undeleted-node.enabled=false
eu.xenit.alfresco.healthprocessor.fixer.elastic-missing-or-outdated-node.enabled=false
eu.xenit.alfresco.healthprocessor.fixer.elastic-missing-or-outdated-node.waitForIndex=true
eu.xenit.alfresco.healthprocessor.fixer.elastic-missing-or-outdated-node.waitIntervalMillis=1000
eu.xenit.alfresco.healthprocessor.fixer.elastic-missing-or-outdated-node.waitIntervalCount=2

search.solrTrackingSupport.ignorePathsForSpecificTypes=false
search.solrTrackingSupport.ignorePathsForSpecificAspects=false