{
 "title": "Inflow Client - Job Related",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "jobName", "label": "Job Name", "query": "label_values(job_name)" },
   { "name": "instance", "label": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Number of jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "inflow_client_jobs_count{instance=\"$instance\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Alfresco Proxy information",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "inflow_client_documents_in_counter_total{job_name=\"$jobName\", operation=\"ready-for-upload-to-alfresco\", instance=\"$instance\"}-inflow_client_documents_out_counter_total{job_name=\"$jobName\", operation=\"ready-for-upload-to-alfresco\", instance=\"$instance\"}",
     "legendFormat": "Waiting for upload to Alfresco"
    },
    {
     "expr": "inflow_client_proxy_available_reports{job_name=\"$jobName\", instance=\"$instance\"}",
     "legendFormat": "Available reports"
    },
    {
     "expr": "inflow_client_proxy_remaining_capacity{job_name=\"$jobName\", instance=\"$instance\"}",
     "legendFormat": "Remaining backend capacity"
    }
   ]
  },
  { "title": "Store Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Store reports - average duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(inflow_client_store_reports_seconds_sum{instance=\"$instance\"}[1m]))/sum(rate(inflow_client_store_reports_seconds_count{instance=\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total reports stored",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "inflow_client_store_reports_count_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Reports stored (ops/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(inflow_client_store_reports_count_total{instance=\"$instance\"}[1m])"
    }
   ]
  },
  { "title": "All Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Processing speed (documents per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "documents / sec" }
   ],
   "targets": [
    {
     "expr": "irate(inflow_client_processed_count_total{status!=\"INPUTQUEUE\", instance=\"$instance\"}[1m])",
     "legendFormat": "Job: '{{ job_name }}'"
    }
   ]
  },
  {
   "title": "Total number of processed documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "documents" }
   ],
   "targets": [
    {
     "expr": "inflow_client_processed_count_total{instance=\"$instance\"}",
     "legendFormat": "Job: '{{job_name}}', status: {{ status }}"
    }
   ]
  },
  {
   "title": "Total number of files in input folder(s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "inflow_client_jobs_fs_input_count{instance=\"$instance\"}",
     "legendFormat": "Job: '{{ job_name }}'"
    }
   ]
  },
  { "title": "Job: '$jobName'", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "jobName" },
  {
   "title": "Processing speed (documents per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "documents / sec" }
   ],
   "targets": [
    {
     "expr": "sum(irate(inflow_client_processed_count_total{status!=\"INPUTQUEUE\", job_name=\"$jobName\", instance=\"$instance\"}[1m]))",
     "legendFormat": "Job: '{{ job_name }}'"
    }
   ]
  },
  {
   "title": "Total number of processed documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "documents" }
   ],
   "targets": [
    {
     "expr": "inflow_client_processed_count_total{job_name=\"$jobName\", instance=\"$instance\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Total number of files in input folder(s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "inflow_client_jobs_fs_input_count{job_name=\"$jobName\", instance=\"$instance\"}",
     "legendFormat": "Job: '{{ job_name }}'"
    }
   ]
  }
 ]
}