{
 "title": "Inflow Backend",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(inflow_backend_store_content_size_bytes_total, instance)"
   },
   { "name": "operation", "query": "label_values(operation)" }
  ]
 },
 "panels": [
  {
   "title": "Buffer usage (packages)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "packages" }
   ],
   "targets": [
    {
     "expr": "inflow_backend_packages_in_counter_total{instance=\"$instance\"}-inflow_backend_packages_out_counter_total{instance=\"$instance\"}",
     "legendFormat": "{{ operation }}"
    },
    {}
   ]
  },
  {
   "title": "Buffer usage (documents)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "documents" }
   ],
   "targets": [
    {
     "expr": "inflow_backend_documents_in_counter_total{instance=\"$instance\"}-inflow_backend_documents_out_counter_total{instance=\"$instance\"}",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Average time per operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(inflow_backend_create_packages_seconds_sum{instance=\"$instance\"}[1m]))/sum(rate(inflow_backend_create_packages_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Create Package [BATCH]"
    },
    {
     "expr": "sum(rate(inflow_backend_retry_create_package_seconds_sum{instance=\"$instance\"}[1m]))/sum(rate(inflow_backend_create_packages_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Create Package [RETRY]"
    },
    {
     "expr": "sum(rate(inflow_backend_store_content_seconds_sum{instance=\"$instance\"}[1m]))/sum(rate(inflow_backend_store_content_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Store Content"
    },
    {
     "expr": "sum(rate(inflow_backend_find_existing_node_seconds_sum{instance=\"$instance\"}[1m]))/sum(rate(inflow_backend_find_existing_node_seconds_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "Find Existing Node"
    }
   ]
  },
  { "title": "Create Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Create Packages [BATCH] (documents/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "documents/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(inflow_backend_create_packages_documents_counter{instance=\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Create Packages [BATCH] (transactions/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "transactions/s" }
   ],
   "targets": [
    {
     "expr": "rate(inflow_backend_create_packages_seconds_count{instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Create Packages [BATCHED]: package count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(inflow_backend_create_packages_packages_counter{instance=\"$instance\"})",
     "legendFormat": "# packages"
    },
    {
     "expr": "inflow_backend_create_packages_documents_counter{instance=\"$instance\"}",
     "legendFormat": "# documents with status {{ status }}"
    }
   ]
  },
  {
   "title": "Create Packages [BATCHED] request histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(inflow_backend_create_packages_seconds_bucket{instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "95% percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(inflow_backend_create_packages_seconds_bucket{instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "50% percentile"
    }
   ]
  },
  {
   "title": "Create Package [RETRY] (transactions/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "transactions/s" }
   ],
   "targets": [
    {
     "expr": "rate(inflow_backend_retry_create_package_seconds_count{instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Create Package [RETRY]: package Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "inflow_backend_retry_create_package_documents_counter{instance=\"$instance\"}",
     "legendFormat": "# documents with status {{ status }}"
    }
   ]
  },
  {
   "title": "Create Package [RETRY] request histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(inflow_backend_retry_create_package_seconds_bucket{instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "95% percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(inflow_backend_retry_create_package_seconds_bucket{instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "50% percentile"
    }
   ]
  },
  { "title": "Store Content", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Store Content throughput (ops/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(inflow_backend_store_content_seconds_count{host=\"${host}\"}[1m])"
    }
   ]
  },
  {
   "title": "Store Content througput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(inflow_backend_store_content_size_bytes_total{host=\"${host}\"}[1m])"
    }
   ]
  },
  {
   "title": "Store Content total processed size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "inflow_backend_store_content_size_bytes_total{host=\"${host}\"}"
    }
   ]
  },
  {
   "title": "Store Content requests heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(inflow_backend_store_content_seconds_bucket{host=\"${host}\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Store Content # requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "inflow_backend_store_content_seconds_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Store Content Requests Histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(inflow_backend_store_content_seconds_bucket{instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "95% percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(inflow_backend_store_content_seconds_bucket{instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "50% percentile"
    }
   ]
  },
  { "title": "Find Existing Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Finde Existing Nodes throughput (ops/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(inflow_backend_find_existing_node_seconds_count{host=\"${host}\"}[1m])"
    }
   ]
  },
  {
   "title": "Find Existing Nodes Requests Histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(inflow_backend_find_existing_node_seconds_bucket{instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "95% percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(inflow_backend_find_existing_node_seconds_bucket{instance=\"$instance\"}[1m])) by (le))",
     "legendFormat": "50% percentile"
    }
   ]
  },
  {
   "title": "Finde Existing Nodes average duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(inflow_backend_find_existing_node_seconds_sum{instance=\"$instance\"}[1m]))/sum(rate(inflow_backend_find_existing_node_seconds_count{instance=\"$instance\"}[1m]))"
    }
   ]
  }
 ]
}