{
 "title": "MQ metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "line",
    "label": "Line",
    "query": {
     "query": "label_values(be_pvgroup_alfresco_mq_queues{env=~\"$env\"},line)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(be_pvgroup_alfresco_mq_queues{env=~\"$env\",line=~\"$line\"},service)"
    }
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": {
     "query": "label_values(be_pvgroup_alfresco_mq_queues{env=~\"$env\",line=~\"$line\",service=~\"$service\"},queue)"
    }
   },
   {
    "name": "clientId",
    "label": "Client Id",
    "query": {
     "query": "label_values(be_pvgroup_alfresco_mq_connections{env=~\"$env\",line=~\"$line\",service=~\"$service\"},clientId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(be_pvgroup_alfresco_mq_connections{state=\"started\",env=~\"$env\",line=~\"$line\",service=~\"$service\",clientId=~\"$clientId\"})",
     "legendFormat": "started"
    },
    {
     "expr": "sum(be_pvgroup_alfresco_mq_connections{state=\"closed\",env=~\"$env\",line=~\"$line\",service=~\"$service\",clientId=~\"$clientId\"})",
     "legendFormat": "closed"
    }
   ]
  },
  {
   "title": "notifications",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "be_pvgroup_alfresco_mq_notifications{state=\"success\",env=~\"$env\",line=~\"$line\",service=~\"$service\"}",
     "legendFormat": "success"
    },
    {
     "expr": "be_pvgroup_alfresco_mq_notifications{state=\"failed\",env=~\"$env\",line=~\"$line\",service=~\"$service\"}",
     "legendFormat": "failed"
    },
    {
     "expr": "be_pvgroup_alfresco_mq_notifications{state=\"skipped\",env=~\"$env\",line=~\"$line\",service=~\"$service\"}",
     "legendFormat": "skipped"
    }
   ]
  },
  {
   "title": "sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "be_pvgroup_alfresco_mq_sessions{state=\"created\",env=~\"$env\",line=~\"$line\",service=~\"$service\"}",
     "legendFormat": "created"
    },
    {
     "expr": "be_pvgroup_alfresco_mq_sessions{state=\"committed\",env=~\"$env\",line=~\"$line\",service=~\"$service\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "be_pvgroup_alfresco_mq_sessions{state=\"rollbacks\",env=~\"$env\",line=~\"$line\",service=~\"$service\"}",
     "legendFormat": "rollbacks"
    },
    {
     "expr": "be_pvgroup_alfresco_mq_sessions{state=\"closed\",env=~\"$env\",line=~\"$line\",service=~\"$service\"}",
     "legendFormat": "closed"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "repeat": "queue",
   "targets": [
    {
     "expr": "be_pvgroup_alfresco_mq_queues{state=\"success\",queue=~\"$queue\",env=~\"$env\",line=~\"$line\",service=~\"$service\"}",
     "legendFormat": "success"
    },
    {
     "expr": "be_pvgroup_alfresco_mq_queues{state=\"failed\",queue=~\"$queue\",env=~\"$env\",line=~\"$line\",service=~\"$service\"}",
     "legendFormat": "failed"
    },
    {
     "expr": "be_pvgroup_alfresco_mq_queues{state=\"skipped\",queue=~\"$queue\",env=~\"$env\",line=~\"$line\",service=~\"$service\"}",
     "legendFormat": "skipped"
    }
   ]
  }
 ]
}