{
 "title": "Spring Boot Statistics & Endpoint Metrics",
 "description": "Dashboard for Spring Boot2 Statistics(by micrometer-prometheus).\nThis is a fork of dashboard 6756, fixed for Spring Boot 2.3 and support for Jetty instead of Tomcat along with scraping endpoints' metrics.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes, instance)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(jvm_classes_loaded_classes{instance=\"$instance\"}, job)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{instance=\"$instance\", job=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{job=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{job=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{job=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{job=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", job=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", job=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\", job=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\", job=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\", job=\"$application\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Sum",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{instance=\"$instance\", job=\"$application\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Max",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{instance=\"$instance\", job=\"$application\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "repeat": "memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", job=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", job=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", job=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "repeat": "memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", job=\"$application\", id=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", job=\"$application\", id=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", job=\"$application\", id=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", job=\"$application\", id=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", job=\"$application\", id=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", job=\"$application\", id=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", job=\"$application\", id=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", job=\"$application\", id=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", job=\"$application\", id=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", job=\"$application\", id=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", job=\"$application\", id=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", job=\"$application\", id=~\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{instance=\"$instance\", job=\"$application\"}",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$instance\", job=\"$application\"}[5m])",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", job=\"$application\", id=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", job=\"$application\", id=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", job=\"$application\", id=\"mapped\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", job=\"$application\", id=\"mapped\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{instance=\"$instance\", job=\"$application\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live_threads{instance=\"$instance\", job=\"$application\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak_threads{instance=\"$instance\", job=\"$application\"}",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", job=\"$application\"}[5m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", job=\"$application\"}[5m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\", job=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", job=\"$application\"}[5m])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", job=\"$application\", uri!~\".*actuator.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\", job=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\", job=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", job=\"$application\", level=\"info\"}[5m])",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", job=\"$application\", level=\"error\"}[5m])",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 111 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", job=\"$application\", level=\"warn\"}[5m])",
       "legendFormat": "warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DEBUG logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 111 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", job=\"$application\", level=\"debug\"}[5m])",
       "legendFormat": "debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "TRACE logs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 111 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", job=\"$application\", level=\"trace\"}[5m])",
       "legendFormat": "trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}