logger.eu_xenit_alfresco_healthprocessor_example.name=eu.xenit.alfresco.healthprocessor.example
logger.eu_xenit_alfresco_healthprocessor_example.level=info

logger.elastic_debug.name=org.alfresco.repo.search.impl.elasticsearch
logger.elastic_debug.level=debug
logger.elastic_init_trace.name=org.alfresco.repo.search.impl.elasticsearch.contentmodelsync.ElasticsearchInitialiser
logger.elastic_init_trace.level=trace