{
 "title": "Threshold indexing strategy",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Current and max. transaction ID",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "eu_xenit_alfresco_healthprocessor_indexing_threshold_current_transaction_id",
     "legendFormat": "__auto"
    },
    {
     "expr": "eu_xenit_alfresco_healthprocessor_indexing_threshold_max_transaction_id",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active background threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "eu_xenit_alfresco_healthprocessor_indexing_threshold_running_background_threads",
     "legendFormat": "__auto"
    },
    {
     "expr": "eu_xenit_alfresco_healthprocessor_indexing_threshold_transaction_fetcher_running",
     "legendFormat": "__auto"
    },
    {
     "expr": "eu_xenit_alfresco_healthprocessor_indexing_threshold_running_transaction_mergers",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued transaction batches (to be processed)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "eu_xenit_alfresco_healthprocessor_indexing_threshold_queued_transaction_batches",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued node batches (to be exported)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "eu_xenit_alfresco_healthprocessor_indexing_threshold_queued_nodes",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}