package eu.xenit.alfresco.healthprocessor.reporter.api;

import eu.xenit.alfresco.healthprocessor.plugins.api.HealthProcessorPlugin;
import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import lombok.Value;

/**
 * End-of-cycle summary of a certain {@link HealthProcessorPlugin} for {@link HealthReporter}s
 */
@Value
public class ProcessorPluginOverview {

    /**
     * Class of the {@link HealthProcessorPlugin} that created the reports for which this summary is created.
     */
    @Nonnull
    Class<? extends HealthProcessorPlugin> pluginClass;

    /**
     * Map containing a counter in how many reports a certain {@link NodeHealthStatus} was generated.
     */
    @Nonnull
    Map<NodeHealthStatus, Long> countsByStatus;

    /**
     * List of reports generated by the {@link HealthProcessorPlugin}.
     *
     * Note that not all reports may be present in the overview.
     *
     * @implNote Only a subset of reports are stored in the overview:
     * <ul>
     *     <li>Only reports of state {@link NodeHealthStatus#UNHEALTHY}, {@link NodeHealthStatus#UNREPORTED} and {@link NodeHealthStatus#FIXED} are available in the overview.</li>
     *     <li>There is a configurable, global cut-off for the number of reports that are stored. Reports arriving after the cut-off value has been reached are not available from the overview.</li>
     * </ul>
     */
    @Nonnull
    List<NodeHealthReport> reports;
}
