#https://grafana.com/docs/tempo/latest/configuration

server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ":4317"  # Enable gRPC on port 4317
        # http:
        #   endpoint: ":4318"  # Optional: Enable HTTP on port 4318
#                                     # maximum length of time before cutting a block
#                                     # (default: 30m)
#ingester:
#  max_block_duration: 5m               # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally

#compactor:
#  compaction:
#    block_retention: 1h  (default 14 days(336h))              # overall Tempo trace retention. set for demo purposes


metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

storage:
  trace:
    backend: local                     # backend configuration to use
    wal:
      path: /tmp/tempo/wal             # where to store the the wal locally
    local:
      path: /tmp/tempo/blocks

overrides:
  metrics_generator_processors: [service-graphs, span-metrics] # enables metrics generator