## Scenario 11
version: '3.2'
services:
  solr:
    environment:
      - GLOBAL_ALL_alfresco.cron=0 0/5 * * * ? *
      - GLOBAL_ALL_alfresco.newSearcherInterval=300000 #every 5 min, to avoid unnecessary CPU during reindexing
#      - GLOBAL_ALL_alfresco.nodeBatchSize=1000
#      - GLOBAL_ALL_alfresco.transactionDocsBatchSize=1000
#      - GLOBAL_ALL_alfresco.corePoolSize=64
#      - GLOBAL_ALL_merger.maxMergeCount=16
#      - GLOBAL_ALL_merger.maxThreadCount=7
      - GLOBAL_ALL_merge.policy.maxMergedSegmentMB=256
      - GLOBAL_ALL_merge.policy.maxMergeAtOnce=40
      - GLOBAL_ALL_merge.policy.segmentsPerTier=20
      - GLOBAL_ALL_alfresco.metadata.tracker.timestep=86400000

