cache.healthProcessorSharedCache.tx.maxItems=0
cache.healthProcessorSharedCache.tx.statsEnabled=${caches.tx.statsEnabled}
cache.healthProcessorSharedCache.maxItems=0
cache.healthProcessorSharedCache.timeToLiveSeconds=0
cache.healthProcessorSharedCache.maxIdleSeconds=0
cache.healthProcessorSharedCache.eviction-policy=NONE
cache.healthProcessorSharedCache.cluster.type=fully-distributed
cache.healthProcessorSharedCache.backup-count=1
# Alfresco supports policy names with "hz." prefix to bridge API/version differences
cache.healthProcessorSharedCache.merge-policy=hz.LATEST_UPDATE
cache.healthProcessorSharedCache.readBackupData=false