name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        run: ./gradlew test
#      - name: Upload analysis to sonarcloud
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          GITHUB_TOKEN: ${{ github.token }}
#        run: ./gradlew sonarqube -Dsonar.projectKey=alfresco-health-processor -Dsonar.organization=xenit-eu -Dsonar.host.url=https://sonarcloud.io