name: CI

on:
  push:
  pull_request:
env:
  GRADLE_OPTS: >-
    -Dorg.gradle.project.org.alfresco.maven.nexus.username=${{ secrets.ALFRESCO_NEXUS_USERNAME }} 
    -Dorg.gradle.project.org.alfresco.maven.nexus.password=${{ secrets.ALFRESCO_NEXUS_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - &checkout:
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - &setupJava:
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Test
        run: ./gradlew test
      - name: Upload reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports-test
          path: alfresco-health-processor-platform/build/reports
      - name: Upload analysis to sonarcloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew aggregateJacocoReport sonar --stacktrace
  integration-test:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' || github.base_ref == 'master' || startsWith(github.ref, 'refs/tags/') }}
    strategy:
      matrix:
        edition: [ "community-231", "enterprise-251" ]
    steps:
      - <<: *checkout
      - <<: *setupJava
      - name: Test
        run: ./gradlew :integration-tests:alfresco-${{ matrix.edition }}:integrationTest -Prandom_ports=true
      - name: Upload reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports-integration-test-${{ matrix.edition }}
          path: integration-tests/alfresco-${{ matrix.edition }}/build/reports
  publish:
    needs: [test, integration-test]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - <<: *checkout
      - <<: *setupJava
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatype_username: ${{ secrets.SONATYPE_S01_USERNAME }}
          ORG_GRADLE_PROJECT_sonatype_password: ${{ secrets.SONATYPE_S01_PASSWORD }}
        run: ./gradlew publish -PsigningKeyId=CDE3528F
