name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        run: ./gradlew test
      - name: Upload reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: reports-test
          path: alfresco-health-processor-platform/build/reports
      - name: Upload analysis to sonarcloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew aggregateJacocoReport sonarqube
      - name: Javadoc
        run: ./gradlew javadoc
  integration-test:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/master') || startsWith(github.base_ref, 'master') || startswith(github.ref, 'refs/heads/release') }}
    strategy:
      matrix:
        flavour: [ "community" ]
        version: [ "52", "61", "62", "70" ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        run: ./gradlew :integration-tests:alfresco-${{ matrix.flavour }}-${{ matrix.version }}:integrationTest -Prandom_ports=true
      - name: Upload reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: reports-integration-test-${{ matrix.flavour }}-${{ matrix.version }}
          path: integration-tests/alfresco-${{ matrix.flavour }}-${{ matrix.version }}/build/reports
  publish:
    needs: [test, integration-test]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/master') || startswith(github.ref, 'refs/heads/release') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatype_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_sonatype_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: ./gradlew publish -PsigningKeyId=CDE3528F
